creating the entities
Gutovp1/oyster-stream pull request #1
Opened 2024-03-15 22:51 UTC by Gutovp1

Create the typed basic entities of the project.

2024-03-18 13:28 UTC, Daymannovaes requested changes
Opa, ficou bom, só uns detalhezinhos. E também por favor coloque 1 entidade por arquivo.

2024-03-18 13:28 UTC, Daymannovaes commented on entities/entities.ts
> +  type: "nursery" | "intermediate" | "definitive"; //
coloca esses tipos num enum externo, com algum nome descritivo, por exemplo `enum LaternType`

Esse enum pode estar no mesmo arquivo do lanterna.ts, mas exporta ele também

2024-03-18 13:28 UTC, Daymannovaes commented on entities/entities.ts
> +  type: "baby" | "medium" | "large";
mesma coisa aqui, coloca um enum externo

2024-03-18 13:28 UTC, Daymannovaes commented on entities/entities.ts
> +  start_date_in_sea: Date;
pra datas eu gosto do formato `_at`. E gostei aqui do seu `_in_sea`, ficou melhor que o modelo que criei.

Então vc pode atualizar o modelo no notion, e depois atualizar aqui também. Pode ser algo como `in_sea_started_at` ou algo do tipo

2024-03-22 23:30 UTC, Gutovp1 commented
Eu crie os arquivos separadamente por entidade, como você havia sugerido.

Vou subir outra branch com outra ideia. Ao invés de separarmos as entities por tipo (lanterna, caixa, bandeja), pensei em criar um tipo único chamado container que vai ter esses tipos. Acho que vai simplificar, uma vez que eles tem basicamente as mesmas propriedades.

2024-04-07 16:16 UTC, closed without merging